const p1 =document.getElementById('p1')
const p2 =document.getElementById('p2')
const p3 =document.getElementById('p3')
const p4 =document.getElementById('p4')
const pp1 =document.getElementById('2p1')
const pp2 =document.getElementById('2p2')
const pp3 =document.getElementById('2p3')
const pp4 =document.getElementById('2p4')
const content1 =document.getElementById('content1')
const content2 =document.getElementById('content2')
const content3 =document.getElementById('content3')
const content4 =document.getElementById('content4')

p1.addEventListener('click', function() {
    content1.classList.add('show')
    content2.classList.remove('show')
    content3.classList.remove('show')
    content4.classList.remove('show')
    p1.classList.add('active')
    p2.classList.remove('active')
    p3.classList.remove('active')
    p4.classList.remove('active')
})
p2.addEventListener('click', function() {
    content2.classList.add('show')
    content1.classList.remove('show')
    content3.classList.remove('show')
    content4.classList.remove('show')
    p2.classList.add('active')
    p1.classList.remove('active')
    p3.classList.remove('active')
    p4.classList.remove('active')
})
p3.addEventListener('click', function() {
    content3.classList.add('show')
    content2.classList.remove('show')
    content1.classList.remove('show')
    content4.classList.remove('show')
    p3.classList.add('active')
    p2.classList.remove('active')
    p1.classList.remove('active')
    p4.classList.remove('active')
})
p4.addEventListener('click', function() {
    content4.classList.add('show')
    content2.classList.remove('show')
    content3.classList.remove('show')
    content1.classList.remove('show')
    p4.classList.add('active')
    p2.classList.remove('active')
    p3.classList.remove('active')
    p1.classList.remove('active')
})
